pipeline {
    agent any
    tools {
        nodejs 'nodejs-18-20-6'
    }
    environment {
        MONGOURI = "mongodb+srv://cluster0.awxhn.mongodb.net/retryWrites=true&w=majority"
        MONGO_USER = "sai"
        MONGO_PASSWORD = "secret32412"
        PORT = 2121
        GIT_TOKEN = credentials('githubtoken')
        

    }

    options {
        disableResume()
        disableConcurrentBuilds(abortPrevious: true)
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'pre-prod', url: 'https://github.com/iam-narasimhasai/GoalsApp'
            }
        }

        stage('Installing Dependencies') {
            options { timestamps() }
            steps {
                sh '''
                    cd backend
                    npm install
                '''
            }
        }



        stage('Run Unit Testing') {
            options { retry(3) }
            steps {
                sh '''
                    cd backend
                    npm run test
                '''
            }
        }

        stage('Code Coverage') {
            steps {
                catchError(message: 'Oops! it will be fixed in future', stageResult: 'UNSTABLE') {
                    sh '''
                        cd backend
                        npm run coverage
                    '''
                }
            }
        }



        stage('Build Docker Image') {
            steps {
                sh '''
                    cd backend/
                    
                    docker build -t narasimhasai95/goalsapi:${GIT_COMMIT} .
                '''
            }
        }

        stage('Trivy Docker Image Scan') {
            steps {
                sh '''
                    mkdir -p trivy-report
                    trivy image --severity CRITICAL,HIGH,MEDIUM --format template --template "@/var/lib/jenkins/html.tpl" -o trivy-report/vulnerability-report.html narasimhasai95/goalsapi:${GIT_COMMIT}
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry(credentialsId: 'docker-creds', url: "") {
                    sh 'docker push narasimhasai95/goalsapi:${GIT_COMMIT}'
                }
            }
        }

        stage('Docker Image Update') {
            steps {
                
                   sh 'git clone -b main https://github.com/iam-narasimhasai/GoalsApp_Manifest'
                   dir("GoalsApp_Manifest") {
                    sh '''
                    git checkout main
                    sed -i "s#narasimhasai95.*#narasimhasai95/goalsapi:${GIT_COMMIT}#g" deploy-backend.yaml

                    cat deploy-backend.yaml
                    
                    git config --global user.email "narasimhasai.nimmagadda@gmail.com"
                    git remote set-url origin https://$GIT_TOKEN@github.com/iam-narasimhasai/GoalsApp_Manifest
                    git add .
                    git commit -am "Updated the docker image ${GIT_COMMIT}"
                    git push -u origin main

                    '''
                   }
                
            }
        }







    }

    post {
        always {
            
            script {
                if(fileExists('GoalsApp_Manifest')){
                    sh 'rm -rf GoalsApp_Manifest'
                }
            }

            junit allowEmptyResults: true, testResults: 'backend/test-results.xml'

            publishHTML([
                allowMissing: true, 
                alwaysLinkToLastBuild: true, 
                keepAll: true, 
                reportDir: 'backend/coverage/lcov-report', 
                reportFiles: 'index.html', 
                reportName: 'Code Coverage HTML Report', 
                useWrapperFileDirectly: true
            ])

            publishHTML([
                allowMissing: true, 
                alwaysLinkToLastBuild: true, 
                keepAll: true, 
                reportDir: 'trivy-report', 
                reportFiles: 'vulnerability-report.html', 
                reportName: 'Trivy Vulnerability Report', 
                useWrapperFileDirectly: true
            ])
        }
    }
}
