name: 321 Testing

on:
  push:
  workflow_dispatch:

env:
  MONGO_URL: "mongodb+srv://sai:secret32412@cluster0.awxhn.mongodb.net/course-goals?retryWrites=true&w=majority"
  PORT: "3000"

permissions:
  contents: write

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend/
          pwd
          npm install

      - name: install httpie
        run: sudo apt install httpie

      - name: running app
        run: |
          cd backend/
          node app.js
          http GET http://localhost:3000/goals

      - name: Run Unit Test for backend app
        run: |
          curl http://localhost:3000/goals | jq
          ls -ltra
          cd backend/
          pwd
          npm run test -- --verbose
          ls -ltra
        
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            backend/test-results.xml
          if-no-files-found: ignore