name: backend Testing  

on:
  push:
  workflow_dispatch:
   

env:
  MONGO_URL: ${{secrets.MONGO_URL}}
  PORT: "4321"

permissions:
  contents: write

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend/
          pwd
          npm install
          
      - name: steppppp
        run: sudo setcap 'cap_net_bind_service=+ep' backend/app.js
        
      - name: Run Unit Test for backend app
        run: |
          ls -ltra
          cd backend/
          pwd
          npm run test -- --verbose 
          sudo PORT=4321 npm start & sudo sleep 5

      - name: code coverage
        run: |
          cd backend/
          npm run coverage

      - name: Test server
        run: curl http://localhost:321/goals   
        
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            backend/test-results.xml
          if-no-files-found: ignore