name: backend Testing  

on:
  workflow_dispatch:
  push:
    branches:
      - pre-prod
  
   

env:
  MONGO_URL: ${{secrets.MONGO_URL}}
  PORT: ${{vars.PORT}}

permissions:
  contents: write

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18,19,20]
        os: [ubuntu-latest,windows-latest]
        exclude:
          - nodejs_version: 18
            os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version - ${{matrix.nodejs_version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.nodejs_version}}

      - name: Install Dependencies
        run: |
          cd backend/
          pwd
          npm install
          
      
      - name: code coverage
        run: |
          cd backend/
          npm run coverage
      
      - name: Run Unit Test for backend app
        run: |
            ls -ltra
            cd backend/
            pwd
            npm run test -- --verbose 
            sudo PORT=$PORT npm start & sleep 5
      
        
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/test-results.xml
          
