name: backend Testing  

on:
  workflow_dispatch:
  push:
    branches:
      - pre-prod
  
   

env:
  MONGO_URL: ${{secrets.MONGO_URL}}
  PORT: ${{vars.PORT}}

permissions:
  contents: write

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        nodejs_version: [18,19,20]
        os: [ubuntu-latest]
        
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version - ${{matrix.nodejs_version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.nodejs_version}}

      - name: Install Dependencies
        run: |
          cd backend/
          npm install
      
      - name: Run Unit Test for backend app
        continue-on-error: true
        run: |
            cd backend/
            npm run test -- --verbose 
            sudo PORT=$PORT npm start & sleep 5
      
        
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results on ${{matrix.os}} with node version ${{matrix.nodejs_version}}
          path: backend/test-results.xml
  
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs Version - 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: |
         cd backend/
         npm install

      - name: Check Code Coverage
        continue-on-error: true
        id: nodecoverage
        run: |
         cd backend/
         npm run coverage

      - name: Archive Test Results
        if: steps.nodecoverage.outcome == 'failure' && steps.nodecoverage.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: backend/coverage
          retention-days: 5
