name: stage Unit Testing

on:
  push:
  workflow_dispatch:


env:
  MONGO_URL: "mongodb+srv://sai:secret32412@cluster0.awxhn.mongodb.net/course-goals?retryWrites=true&w=majority"
  PORT: "321"

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend/
          pwd
          sudo npm install

      - name: Run Unit Tests for backend app
        run: |
          ls -ltra
          cd backend/
          pwd
          sudo npm test 
          ls -ltra

      - name: upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: test-results.xml
          path: backend/test-results.xml