name: Solar System Workflow

on:
  workflow_dispatch

env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  PORT: ${{ vars.PORT }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Version 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: going to backend folder
        run: |
            ls -ltra

      - name: Install Dependencies
        run: |
            cd GoalsApp/backend/
            pwd
            npm install

      - name: Run Unit Tests for backend app
        run: |
            pwd
            npm test
